//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanVeXePhuongTrang.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChuyenDi
    {
        public tblChuyenDi()
        {
            this.tblChiTietChuyenDis = new HashSet<tblChiTietChuyenDi>();
            this.tblChiTietPhieuDatChoes = new HashSet<tblChiTietPhieuDatCho>();
        }
    
        public int MaChuyenDi { get; set; }
        public Nullable<int> MaXe { get; set; }
        public Nullable<System.DateTime> KhoiHanh { get; set; }
        public Nullable<System.DateTime> KetThuc { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public Nullable<int> SoGheTrong { get; set; }
        public Nullable<int> SoGheDat { get; set; }
    
        public virtual tblBaoCaoDoanhThuChuyenDi tblBaoCaoDoanhThuChuyenDi { get; set; }
        public virtual ICollection<tblChiTietChuyenDi> tblChiTietChuyenDis { get; set; }
        public virtual ICollection<tblChiTietPhieuDatCho> tblChiTietPhieuDatChoes { get; set; }
        public virtual tblXeKhach tblXeKhach { get; set; }
    }
}
