//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanVeXePhuongTrang.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChiTietChuyenDi
    {
        public int MaChuyenDi { get; set; }
        public string MaBenXeTrungGiang { get; set; }
        public Nullable<int> ThoiGianDung { get; set; }
        public string GhiChu { get; set; }
    
        public virtual tblBenXe tblBenXe { get; set; }
        public virtual tblChuyenDi tblChuyenDi { get; set; }
    }
}
