//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanVeXePhuongTrang.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLoaiNhanVien
    {
        public tblLoaiNhanVien()
        {
            this.tblNhanViens = new HashSet<tblNhanVien>();
        }
    
        public int MaLoaiNhanVien { get; set; }
        public string TenLoaiNhanVien { get; set; }
    
        public virtual ICollection<tblNhanVien> tblNhanViens { get; set; }
    }
}
