//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanVeXePhuongTrang.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNhanVien
    {
        public tblNhanVien()
        {
            this.tblTaiKhoans = new HashSet<tblTaiKhoan>();
            this.tblXeKhaches = new HashSet<tblXeKhach>();
            this.tblXeTrungChuyens = new HashSet<tblXeTrungChuyen>();
        }
    
        public int MaNhanVien { get; set; }
        public string TenNhanVien { get; set; }
        public Nullable<int> MaLoaiNhanVien { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public Nullable<int> CMND { get; set; }
        public string DiaChi { get; set; }
    
        public virtual tblLoaiNhanVien tblLoaiNhanVien { get; set; }
        public virtual ICollection<tblTaiKhoan> tblTaiKhoans { get; set; }
        public virtual ICollection<tblXeKhach> tblXeKhaches { get; set; }
        public virtual ICollection<tblXeTrungChuyen> tblXeTrungChuyens { get; set; }
    }
}
