//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanVeXePhuongTrang.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblXeKhach
    {
        public tblXeKhach()
        {
            this.tblChuyenDis = new HashSet<tblChuyenDi>();
        }
    
        public int MaXe { get; set; }
        public Nullable<int> MaTaiXe { get; set; }
        public Nullable<int> MaLoaiXe { get; set; }
        public string BienSoXe { get; set; }
        public string MaTuyen { get; set; }
        public Nullable<int> SoGhe { get; set; }
    
        public virtual ICollection<tblChuyenDi> tblChuyenDis { get; set; }
        public virtual tblLoaiXe tblLoaiXe { get; set; }
        public virtual tblNhanVien tblNhanVien { get; set; }
        public virtual tblTuyenXe tblTuyenXe { get; set; }
    }
}
